### PR TITLE
lefty flip pro drums red cymbal input fix

### LINKED ISSUE #173: red cymbal input does not work in lefty pro drums
the green cymbal input in lefty pro drums should trigger the red cymbal instead

### PR DESCRIPTION
**Pull request by santorfo**
Fixes #173 

In the previous implementation, the lefty flip red cymbal input was being read as a regular red cymbal, which doesn't exist. 
Pro Drums lefty flip implies the player has moved the Green cymbal above the Red snare, so whilst the chart has flipped, and so have the inputs, that specific input stays the same because the input object was physically moved.

### CODE REVIEW

File: Assets/Script/PlayMode/DrumsTrack.cs [hunk 1]
```diff
@@ -237,7 +237,11 @@ public sealed class DrumsTrack : AbstractTrack {
 						drum = kickIndex == 4 ? 1 : 2;
 						break;
 					case 3:
-						drum = kickIndex == 4 ? 0 : 1;
+						// lefty flip on pro drums means physically moving the green cymbal above the red snare
+						// so while the position on the chart has changed, the input object is the same
+						if (!cymbal){
+							drum = kickIndex == 4 ? 0 : 1;
```
Comment (DarkRTA) [inline Assets/Script/PlayMode/DrumsTrack.cs:243]: have you checked and made sure this doesn't swap the yellow and blue cymbals as well?

**Review by DarkRTA — CHANGES_REQUESTED** [review]

File: Assets/Script/PlayMode/DrumsTrack.cs (hunk 1 above)
Comment (DarkRTA) [reply Assets/Script/PlayMode/DrumsTrack.cs:243]: nvm the diff didn't show the rest of the file
this is correct

Comment (santorfo) [reply Assets/Script/PlayMode/DrumsTrack.cs:243]: is it not supposed to? The regular drums left flip has them swapped too...
